---
ansible_ssh_common_args: '-F ssh/config'
ansible_python_interpreter: "{{ python_fullpath | default('/usr/bin/python3') }}"

clickhouse_shards:
- {cluster_name: 'cluster01', shard_id: '01'}
- {cluster_name: 'cluster02', shard_id: '02'}

clickhouse_servers:
- {host: 'ch-c01-s01-r01', cluster_name: 'cluster01', shard_id: '01', replica_id: '01'}
- {host: 'ch-c01-s01-r02', cluster_name: 'cluster01', shard_id: '01', replica_id: '02'}
- {host: 'ch-c01-s02-r01', cluster_name: 'cluster02', shard_id: '02', replica_id: '01'}
- {host: 'ch-c01-s02-r02', cluster_name: 'cluster02', shard_id: '02', replica_id: '02'}

clickhouse_keeper_attrs:
- {host: keeper01, server_id: '1'}
- {host: keeper02, server_id: '2'}
- {host: keeper03, server_id: '3'}

grafana_clickhouse_user: "grafana"
grafana_clickhouse_password: "grafana_password"

otel_database: "otel"
otel_collector_clickhouse_user: "otel_collector"
otel_collector_clickhouse_password: "otel_collector_password"

otelcol_contrib_version: "0.116.1"
