- name: Set up a ClickHouse cluster
  hosts: all
  roles:
  - role: rsync
  - role: clickhouse_apt_repo
  - role: clickhouse_keeper
    when: inventory_hostname in groups["keepers"]
  - role: clickhouse
    when: inventory_hostname in groups["databases"]
  - role: otelcol_contrib
    when: inventory_hostname in groups["databases"]
  - role: grafana_oss
    when: inventory_hostname in groups["grafanas"]
