[project]
name = "clickhouse-ansible-playbook"
version = "0.1.0"
description = "An Ansible playbook to set up a ClickHouse cluster."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ansible>=10.5.0",
]
