---
- name: Get otelcol-contrib installed version
  command: dpkg-query -f '${Version}' -W otelcol-contrib
  register: otelcol_contrib_installed_version_result
  changed_when: false
  failed_when: false
  check_mode: false

- block:

  - name: Install xz-utils deb package needed to download and install remote deb with Ansible apt module
    # https://docs.ansible.com/ansible/2.9/modules/apt_module.html#apt-module
    # Requires the xz-utils package to extract the control file of the deb package to install.
    apt:
      name: xz-utils

  - name: Download and install otelcol-contrib deb package
    apt:
      deb: "https://github.com/open-telemetry/opentelemetry-collector-releases/releases/download/v{{ otelcol_contrib_version }}/otelcol-contrib_{{ otelcol_contrib_version }}_linux_amd64.deb"
      install_recommends: false

  when: otelcol_contrib_installed_version_result.stdout|default('') != otelcol_contrib_version
